[pytest]
pythonpath = . fusion clsp
log_format = %(asctime)s %(levelname)s %(message)s
log_date_format = %Y-%m-%d %H:%M:%S
log_cli = true
log_cli_level = DEBUG

env =
    PREFIX=txch
    TESTNET=testnet11
    FINGERPRINT=734152856
    CHIA_ROOT=~/.chia/mainnet
    BACKOFF_RETRY_COUNT=30
    BACKOFF_RETRY_WAIT_SECS=1
